### ISSUE TITLE
undefined method 'verify_create'

### ISSUE THREAD

**Issue by vdlindenmark** [messagebird/ruby-rest-api#13]
I installed this gem following your instructions, and want to do something with `client.verify_create`. But i'm getting this error: `<NoMethodError: undefined method 'verify_create' for #<MessageBird::Client:0x007f9c96c9c2e8>>`.

When i take a look at the gem folder, i see the `verify.rb` file is missing. This one is also missing inside the zip of [V1.3.2](https://github.com/messagebird/ruby-rest-api/releases/tag/v1.3.2).
I think that's the reason of this error...?

**Comment by vdlindenmark** [comment]
my code is just this:
```
client = MessageBird::Client.new(YOURE_ACCESS_KEY)
client.verify_create(31612345678, {:reference => "YourReference"})
```

**Comment by vdlindenmark** [comment]
gem install uses an old version of this gem. This commit: https://github.com/messagebird/ruby-rest-api/commit/8d51637c696a0c8b0a73d4959ed81db3bafc8a14 is already in master, but not processed to the gem. I know this because `otp.rb` is still inside the folder and nog `verify.rb`

**Comment by samwierema** [comment]
@vdlindenmark thanks for opening an issue. We'll be submitting a new version of the Gem on Monday.

**Comment by samwierema** [comment]
@vdlindenmark it took two days longer, but version 1.3.3 of the Gem has been released.
