### ISSUE TITLE
NameError: uninitialized constant MessageBird::Client

### ISSUE THREAD

**Issue by ruby24** [messagebird/ruby-rest-api#15]
![image](https://user-images.githubusercontent.com/4975437/41923288-58ffd264-7967-11e8-95b0-f62da2304169.png)

Not a great developer myself, but I get almost everything at least more or less running... Except for your gem.

Running
> require 'pp'
> require 'messagebird'
> client = MessageBird::Client.new("kzO6....[redacted]")

leads to "NameError: uninitialized constant MessageBird::Client"

Ruby version 2.4.1, no errors anywhere else when developing and running short scripts... We're a reasonably big messagebird customer and want to use the script locally to transmit manual passwords to high-volume clients.

Any idea why it's not working? Thanks!

p.s.: Gem is correctly installed and present, had the same issue on the previous messagebird version
> Installing ri documentation for messagebird-rest-1.3.3
> Done installing documentation for messagebird-rest after 0 seconds
> 1 gem installed

**Comment by marcelcorso** [comment]
Hi @ruby24. We've seen this before. 

This happens when there is a problem with the gem installation. Are you using multiple versions of ruby using rvm or rbenv or something like this? 

can you try `gem list`? 

I see you are running the compiler using an IDE. Can you try on the command line?

**Comment by ruby24** [comment]
I'm using rvm, the IDE is textmate (still somehow like it for scripts).

Anyways, tried irb - messagebird is not working there either. Gems seem to be correctly installed in gem list on the command line... and "require messagebird" works in irb.

Also, same in Atom Runner.

Could definitely be that my setup is a bit screwed up, but I don't have any issues with any other gems in scripts or rails projects.

Thanks for taking the time!

<img width="833" alt="screen shot 2018-06-26 at 20 31 38" src="https://user-images.githubusercontent.com/4975437/41932215-b1fd954a-7980-11e8-8f82-88d81454e16a.png">
<img width="1384" alt="screen shot 2018-06-26 at 20 32 31" src="https://user-images.githubusercontent.com/4975437/41932216-b21aa838-7980-11e8-8045-34d210baca86.png">
<img width="334" alt="screen shot 2018-06-26 at 20 32 18" src="https://user-images.githubusercontent.com/4975437/41932217-b234d28a-7980-11e8-8224-c837c3f843a2.png">

**Comment by marcelcorso** [comment]
Yep. Packaging code is never easy!! 😅
Getting the device environment right is super hard!

Just one thing: you have two messagebird gems. The good one is 'messagebird-rest' the other one I'm not sure what it does.

**Comment by ruby24** [comment]
Removed "messagebird-rest" and now it finally works 👍 :)

Really no idea where I got it from, I remember gem install"ing" messagebird and messagebird-rest a few times back and forth when I was testing (got somehow confused by `gem install messagebird-rest` vs `require "messagebird"`).

Thanks so much for the personal tech support during off hours, we're a happy customer :)

p.s.: fyi, accidentally exposed a key in one screenshot, deleted the key in the MB dashboard (and the screenshot here)
