### ISSUE TITLE
new release tag

### ISSUE THREAD

**Issue by mylescc** [messagebird/ruby-rest-api#2]
hey, do you think you could make a v1.1.1 release with the latest changes? Just so then we can target it in our Gem file? Cheers, and thanks

**Comment by prep** [comment]
It's done. I've yet to upload something to rubygems.org, but from your comment I gather that you're pointing directly to the github repo, so you should be good :-)

**Comment by mylescc** [comment]
Yup, still pointing at my fork for now. Thanks! 

MessageBird is awesome btw. looking forward to finally getting it our production branch
