### ISSUE TITLE
Can not send sms messages to a group

### ISSUE THREAD

**Issue by ChrisOdeon** [messagebird/ruby-rest-api#25]
There doesn't seem to be any functionality to send an sms message to a group.

**Comment by marcelcorso** [comment]
Hey Chris, 
Thank you for the issue. I was browsing the docs https://developers.messagebird.com/docs/sms-messaging#send-a-message and there is no way on the public API to send a message to a group. 

This client is just handy a wrapper over the http api so I don't think it's a nice idea to implement it here. 

A better place to implement this is in a code that uses the client. You request the addresses on the group and iterate them (maybe batch them into recipient lists) and then do the POST to /messages. 

I'm closing this now and if you are unsure about the solution let me know!

**Comment by ChrisOdeon** [comment]
> The array of recipients msisdns. Note: can also contain groupIds. Required

**Comment by marcelcorso** [comment]
Oh nice! I missed that. 

So it works already. Or you think the library should make it easier somehow?

**Comment by ChrisOdeon** [comment]
It doesn't seem to work, sorry maybe it's an issue with their API.

**Comment by marcelcorso** [comment]
It *should* work.

Can you please send an email to support@messagebird.com?

Just link to this issue, give them your account email and the group you are
trying to send to and it will be fine.

They will be happy to help you out.

**Comment by ChrisOdeon** [comment]
It seems as though it does work through the api but doesn't work through this sdk because it requires the parameter groupids instead of recipients.

**Comment by marcelcorso** [comment]
oh no. 

Can you please try the "lower level" `request` method? 

Something like 

```
begin
  client.request(:post, "messages", {:originator => "marcel", :body => "monsters", 'groupIds' => ["a9a4bc87700c44ddb6c483bfc192b921"]})
rescue MessageBird::ErrorException => e
  e.errors.inspect
end
```
