### ISSUE TITLE
Whatsapp messages

### ISSUE THREAD

**Issue by ahmadabdelhalim** [messagebird/ruby-rest-api#30]
I want to know if this gem supports sending a message through the WhatsApp channel I created on messagebird, if yes, how can I achieve that?

**Comment by modprobe** [comment]
Hi @ahmadabdelhalim! Support for the Conversations API was added with #29. You can find an example here: https://github.com/messagebird/ruby-rest-api/blob/master/examples/conversation_message.rb

**Comment by ahmadabdelhalim** [comment]
I keep geeting `NoMethodError: undefined method `send_conversation_message' for #<MessageBird::Client:0x00555e2124e580>`

**Comment by modprobe** [comment]
It seems like the latest tagged version (1.4.2) of this was not picked up by rubygems.org, which is still on 1.4.1

@samwierema Can you push the newest version to [rubygems](https://rubygems.org/gems/messagebird-rest)? You're listed as an owner there.

**Comment by ahmadabdelhalim** [comment]
Any update guys? It seems like nobody pushed the branch yet.

**Comment by epels** [comment]
Hi @ahmadabdelhalim: you're completely right, sorry for the delay! I've just pushed `1.4.2` to RubyGems. It's available [here](https://rubygems.org/gems/messagebird-rest/versions/1.4.2).

I assume this resolves the issue, so I'll close it: feel free to reopen it in case you run into any trouble upgrading.

Thanks!
