### ISSUE TITLE
Client.message_list doesn't support all filter options.

### ISSUE THREAD

**Issue by dedman** [messagebird/ruby-rest-api#52]
Hey guys, is there any reason the gem doesn't support all the filter options for the list messages endpoint? There are are lots of filter options listed here https://developers.messagebird.com/api/sms-messaging/#list-messages. But the Client.message_list method only allows limit, offset and status. Is there a reason for this? Can you add the ability to filter other options too?

https://github.com/messagebird/ruby-rest-api/blob/18c39c18d7c3b165c9a77fc039d23ea4a93ffc78/lib/messagebird/client.rb#L253-L265

**Comment by dedman** [comment]
Thanks @Funfun. @marcelcorso any idea when the next release of the gem will be?

**Comment by marcelcorso** [comment]
@dedman release is done!
