### ISSUE TITLE
will version 2 ever be released?

### ISSUE THREAD

**Issue by danleyden** [messagebird/ruby-rest-api#55]
Currently the released version is 1.4.2.

There are many fixes and improvements already lined up in this repo that address issues with that version, along with providing documentation that is not compatible with the released version....

Are there plans to release the new version, or has this now been abandoned?

**Comment by mcls** [comment]
+1 to this.

We recently lost quite a bit of time on a [confusing exception which turned out to be a bug in this API Client](https://github.com/messagebird/ruby-rest-api/issues/17) which had been fixed over a year ago, but still hasn't been released as part of a new version...

**Comment by marcelcorso** [comment]
I'm sorry it took so long but v2.0.0 is here!

https://github.com/messagebird/ruby-rest-api/releases/tag/v2.0.0
https://rubygems.org/gems/messagebird-rest/versions/2.0.0

**Comment by mcls** [comment]
Thanks, Marcel!
