### ISSUE TITLE
begin rescue block missing

### ISSUE THREAD

**Issue by AlejandroMI** [messagebird/ruby-rest-api#65]
Hey! I have run into problems when trying to use the SDK, the error is pointing me to this begin rescue block, looks like part of it went missing after some refactoring. 

https://github.com/messagebird/ruby-rest-api/blame/e3c703f12706b92d35f86bb2f6ebd7eb84a42ce0/lib/messagebird/callflow.rb#L39

https://github.com/messagebird/ruby-rest-api/blame/63332450a4bbc25809e5e01bee303ce2991202f4/lib/messagebird/callflow.rb#L39

**Comment by marcelcorso** [comment]
I talked to @AlejandroMI and he was using an old version of ruby that like things like 

```
something.each |k, v|
   some stuff 
rescue 
   other stuff
end
```

new rubies are ok with that.
